name: themis_ml_dev
channels:
- conda-forge
- defaults
dependencies:
- pydocstyle=2.0.0=py27_0
- snowballstemmer=1.2.1=py27_0
- appnope=0.1.0=py27_0
- backports=1.0=py27_0
- backports_abc=0.5=py27_0
- bleach=1.5.0=py27_0
- configparser=3.5.0=py27_0
- decorator=4.1.2=py27_0
- entrypoints=0.2.3=py27_0
- enum34=1.1.6=py27_0
- flake8=3.3.0=py27_0
- functools32=3.2.3.2=py27_0
- get_terminal_size=1.0.0=py27_0
- html5lib=0.9999999=py27_0
- icu=54.1=0
- ipykernel=4.6.1=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- ipywidgets=6.0.0=py27_0
- jinja2=2.9.6=py27_0
- jsonschema=2.6.0=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=5.1.0=py27_0
- jupyter_console=5.2.0=py27_0
- jupyter_contrib_nbextensions=0.2.8=py27_1
- jupyter_core=4.3.0=py27_0
- markupsafe=1.0=py27_0
- mccabe=0.6.1=py27_0
- mistune=0.7.4=py27_0
- mkl=2017.0.3=0
- nbconvert=5.2.1=py27_0
- nbformat=4.4.0=py27_0
- nose=1.3.7=py27_1
- notebook=5.0.0=py27_0
- numpy=1.13.1=py27_0
- openssl=1.0.2l=0
- pandas=0.20.3=py27_0
- pandocfilters=1.4.2=py27_0
- path.py=10.3.1=py27_0
- pathlib2=2.3.0=py27_0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_1
- prompt_toolkit=1.0.15=py27_0
- ptyprocess=0.5.2=py27_0
- py=1.4.34=py27_0
- pycodestyle=2.3.1=py27_0
- pyflakes=1.5.0=py27_0
- pygments=2.2.0=py27_0
- pyqt=5.6.0=py27_2
- pytest=3.2.1=py27_0
- python=2.7.13=0
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- pyzmq=16.0.2=py27_0
- qt=5.6.2=2
- qtconsole=4.3.1=py27_0
- readline=6.2=2
- scandir=1.5=py27_0
- scikit-learn=0.19.0=np113py27_0
- scipy=0.19.1=np113py27_0
- seaborn=0.8=py27_0
- setuptools=27.2.0=py27_0
- sphinx=1.6.3=py20_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.5.0.1=py27_0
- terminado=0.6=py27_0
- testpath=0.3.1=py27_0
- tk=8.5.18=0
- tornado=4.5.1=py27_0
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=3.0.1=py27_0
- zlib=1.2.11=0
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - ipdb==0.10.3
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.15
