package:
    name: themis-ml
    version: "0.0.4"

source:
    git_rev: v0.0.4
    git_url: https://github.com/cosmicBboy/themis-ml.git

requirements:
  build:
    - python
    - setuptools
    # - scipy
    - pandas
    # - numpy
    - pathlib2
    - scikit-learn >=0.19.1
    - pytest
  run:
    - python
    # - scipy
    # - numpy
    - pandas
    - scikit-learn >=0.19.1
    - pathlib2
    - pytest

test:
  imports:
    - themis_ml
    - pandas
    - numpy
    - pathlib2
    - sklearn
    - pytest

about:
  home: https://github.com/cosmicBboy/themis-ml
  license: MIT
